// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Node struct {
	Nodeid        uuid.UUID
	Nodeurl       string
	ChainID       string
	ChainName     sql.NullString
	LastFetchedAt sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Request struct {
	RequestID     int32
	Nodeid        uuid.UUID
	Responsetime  sql.NullInt64
	Successful    bool
	LastFetchedAt sql.NullTime
}
